#=================================#
#            CronusCore           #
#       Developed by: wroyce      #
#=================================#
# Usage:                          #
#                                 #
# Nether Water:                   #
# cronuscore.netherwater.<world>  #
# cronuscore.netherwater.all      #
# cronuscore.netherwater.bypass   #
#                                 #
# Admin Commands                  #
# cronuscore.admin                #
#=================================#

# You can choose if a command / feature is enable or disabled here (true/false)
discord: true
reload: true
uuid: true
FactionAlerts: true

# Sent to players who use /cc reload
Reload: '&a[!] Configuration reloaded.'

# Sent to players who don't have permission
No-Permission: '&c[!] No Permission'

# Worlds the wither is disabled in
Wither-disabled-worlds:
  - example

# Nether worlds that water is disabled in
nether-water-disabled:
  - someworld

#The radius in which the sponge will soak
sponge-radius: 3

# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html
# eg. DURABILITY:1
BlockedEnchants:
  - example

# Sent to those who are in a faction
Faction-Alerts:
  Joined: "&f(&4!&f) &2&l%Player% &ahas just logged in!"
  Left: "&f(&4!&f) &4&l%Player% &chas just logged out!"

# Sent to players who do /discord
Discord:
  - '&8&l&m|---------[&e&nDiscord&8&l&m]---------|'
  - ' '
  - '        &e&ninsert-link-here'
  - ' '
  - '&8&l&m|---------[&e&nDiscord&8&l&m]---------|'

UUID:
  Self: '&cYour UUID: &8%UUID%'
  Target: "&c%Target%'s UUID: &8%TargetUUID%"

Spawners:
  radius-check: 90

#CHAT FILTER
ChatFilter:
  bypass-permission: 'chatfilter.bypass'
  Message1: "&c&lVexMC &8» &bWe've noticed you''re using &6Profane Language &ba lot. Please keep it to a minimum."

#Example: Hello will be replaced with ****
Replace-Symbol: '*'
#You can continue this list as long as you want just copy my examples above
# NOTE: I do find these words HIGHLY OFFENSIVE and Recommend you keep them
Muted-Words:
  - 'nigger'
  - 'beaner'
  - 'n1gger'
  - 'nibba'
  - 'fuck'
  - 'bitch'
  - 'cunt'
  - 'slut'
  - 'whore'
  - 'ass'
  - 'asshole'

GUI:
  Warp:
    Title: "&6Warp List"
    Size: 45
    Items:
      Nether:
        Name: "&cNether"
        Command: "sudo %player% ewarp nether"
        Lore:
          - "&b"
          - ""
        Slot: 11
      Wastelands:
        Name: "&2Wastelands"
        Command: "sudo %player% ewarp wastelands"
        Slot: 13
      End:
        Name: "&eEnd"
        Command: "sudo %player% ewarp end"
        Slot: 15
      Crates:
        Name: "&bCrates"
        Command: "sudo %player% ewarp crates"
        Slot: 30