name: CronusCore
version: Beta-1.0
description: Dedicated core for CronusPvP
main: mc.wroyce.cronuscore.Core
authors: [wroyce, driftay]

commands:
  cronuscore:
    permission: cronuscore.admin
    aliases: [ccore, cc]
    description: Allows the admin to reload the configuration
  uuid:
    permission: cronuscore.admin
    description: Allows the user to check UUIDs of other players
  warp:
    permission: cronuscore.warp
    description: Allows the user to use /warp
  lastinv:
    permission: cronuscore.lastinv
    description: Allows the user to restore inventories upon pvp via /lastinv
  list:
    permission: cronuscore.list
    description: Allows the user to use /list
  ping:
    permission: cronuscore.ping
    description: Allows the user to use /ping

permissions:
  cronuscore.admin:
    default: op
    description: Permission to allow the user to use admin commands
  cronuscore.warp:
    default: op
    description: Permission to use the warp gui
  cronuscore.chatfilter.bypass:
    default: op
    description: Permission to opt out of the chatfilter
  cronuscore.antitntdamage:
    default: op
    description: Permission to opt out of getting damaged by TNT
  cronuscore.anticreeperdamage:
    default: op
    description: Permission to opt out of getting damaged by creepers
  cronuscore.cant-demote:
    default: false
    description: Permission to opt out of being demoted via /degrant
  cronuscore.lastinv:
    default: op
    description: Permission to restore a players inventory
  cronuscore.list:
    default: true
    description: Permission to view /list
  cronuscore.list.staff:
    default: false
    description: Permissiion to show up as a staff in /list
  cronuscore.list.donator:
    default: false
    description: Permission to show up as a donator in /list
  cronuscore.list.youtube:
    default: false
    description: Permission to show up as a youtuber in /list
  cronuscore.list.partner:
    default: false
    description: Permission to show up as a partner in /list
  cronuscore.list.hidden:
    default: op
    description: Permission to view /list hidden
  cronuscore.ping:
    default: op
    description: Permission to use /ping