name: CronusCore
version: 1.0
description: Dedicated core for CronusPvP
main: main.java.mc.wroyce.cronuscore.Core
authors: [wroyce, driftay]

commands:
  cronuscore:
    permission: cronuscore.admin
    aliases: [ccore, cc]
  uuid:
    permission: cronuscore.admin
  warp:
    permission: cronuscore.warp
  lastinv:
    permission: cronuscore.lastinv
  list:
    permission: cronuscore.list
  ping:
    permission: cronuscore.ping

permissions:
  cronuscore.admin:
    default: op
    description: Permission to allow the user to use admin commands
  cronuscore.warp:
    default: op
    description: Permission to use the warp gui
  cronuscore.chatfilter.bypass:
    default: op
    description: Permission to opt out of the chatfilter
  cronuscore.antitntdamage:
    default: op
    description: Permission to opt out of getting damaged by TNT
  cronuscore.anticreeperdamage:
    default: op
    description: Permission to opt out of getting damaged by creepers
  cronuscore.cant-demote:
    default: false
    description: Permission to opt out of being demoted via /degrant
  cronuscore.lastinv:
    default: op
    description: Permission to restore a players inventory
  cronuscore.list:
    default: true
    description: Permission to view /list
  cronuscore.list.staff:
    default: false
    description: Permissiion to show up as a staff in /list
  cronuscore.list.donator:
    default: false
    description: Permission to show up as a donator in /list
  cronuscore.ping:
    default: op
    description: Permission to use /ping