name: CronusCore
version: 1.0
description: Dedicated core for CronusPvP
main: main.java.mc.wroyce.cronuscore.Core
authors: [wroyce, driftay]

commands:
  cronuscore:
    permission: cronuscore.admin
    aliases: [ccore, cc]
  uuid:
    permission: cronuscore.admin
  warp:
    permission: cronuscore.warp

permissions:
  cronuscore.admin:
    default: op
    description: Permission to allow the user to use admin commands
  cronuscore.warp:
    default: op
    description: Permission to use the warp gui
  cronuscore.chatfilter.bypass:
    default: op
    description: Permission to opt out of the chatfilter
  cronuscore.antitntdamage:
    default: op
    description: Permission to opt out of getting damaged by TNT
  cronuscore.anticreeperdamage:
    default: op
    description: Permission to opt out of getting damaged by creepers